CREATE TABLE Category (
        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar(255) NOT NULL unique
);


CREATE TABLE Expenses (
      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      create_date date NOT NULL,
      amount numeric(15, 2) NOT NULL,
      category_id int references Category(id) ON DELETE CASCADE
);